//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class A_MNTL_STOK_2018
    {
      
        public string MARKA { get; set; }
        public int LOGICALREF { get; set; }
        public string URUNKODU { get; set; }
        public string URETICI_KODU { get; set; }
        public string MODEL { get; set; }
        public Nullable<double> KDV { get; set; }
        public int BAKIYE { get; set; }
        public int BAKIYE2 { get; set; }
        public decimal ListeFiyati { get; set; }
        public int PARABIRIMI { get; set; }
        public int OEM { get; set; }
        public string URUNADI { get; set; }
        public string ARAC { get; set; }
        public Nullable<int> ANABIRIMI { get; set; }
        public string TEDARIKCI { get; set; }
        public string B2B { get; set; }
        public int SizeOzelTL { get; set; }
        public int INDIRIM { get; set; }
        public string CURRSYMB { get; set; }
        public Nullable<int> MSIRANO { get; set; }
        public string Maliyet { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> INDORAN { get; set; }
        public decimal OnerilenFiyat { get; set; }
        public decimal TabanFiyat { get; set; }
        public Nullable<decimal> ALTORAN { get; set; }
    }
}
