//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_INT_CARIONEKRAN_006
    {
        public double GECIKEN { get; set; }
        public string GecikenDurum { get; set; }
        public string Firma_Bilgisi { get; set; }
        public string Durum { get; set; }
        public string KODU { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public double Bakiye { get; set; }
        public double alacak { get; set; }
        public double borc { get; set; }
        public int LOGREF { get; set; }
        public double RiskLimiti { get; set; }
        public string OKoD { get; set; }
        public string LOGOID { get; set; }
    }
}
