//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_SRG_EKSIKSIPARISLER_006_04
    {
        public int LOGICALREF { get; set; }
        public string FICHENO { get; set; }
        public string PLASIYER { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string SPECODE2 { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> SHIPPEDAMOUNT { get; set; }
        public string DURUM { get; set; }
        public Nullable<short> DORESERVE { get; set; }
        public Nullable<double> Kalan { get; set; }
    }
}
