//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class IND_COND
    {
        public int LOGICALREF { get; set; }
        public string NAME { get; set; }
        public string COND1 { get; set; }
        public string COND2 { get; set; }
        public string COND3 { get; set; }
        public Nullable<decimal> ORAN { get; set; }
        public Nullable<decimal> INDORAN { get; set; }
        public Nullable<decimal> ALTORAN { get; set; }
    }
}
