//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISRG_FaturaDetaY_006
    {
        public int LOGICALREF { get; set; }
        public string URUNKODU { get; set; }
        public string URUNADI { get; set; }
        public Nullable<double> URUNMIKTARI { get; set; }
        public Nullable<double> BIRIMFIYAT { get; set; }
        public Nullable<double> SATIRTUTARI { get; set; }
        public Nullable<double> DISTDISC { get; set; }
        public Nullable<double> VATAMNT { get; set; }
        public Nullable<double> VATMATRAH { get; set; }
        public Nullable<int> INVOICEREF { get; set; }
        public Nullable<int> STOCKREF { get; set; }
    }
}
