//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISRG_Hesap_Extresi_006_04
    {
        public Nullable<long> rank { get; set; }
        public int LOGICALREF { get; set; }
        public Nullable<System.DateTime> ISLEMTARIHI { get; set; }
        public string ISLEMACIKLAMASI { get; set; }
        public Nullable<int> BORC_ALACAK { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public string ISLEMTURU { get; set; }
        public string TRANNO { get; set; }
        public Nullable<decimal> TTUTAR { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<int> SOURCEFREF { get; set; }
    }
}
