//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISRG_Faturalar_006
    {
        public int LOGICALREF { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public string FICHENO { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<double> NETTOTAL { get; set; }
        public string drmX { get; set; }
        public int CariRef { get; set; }
        public Nullable<double> MASRAF { get; set; }
        public Nullable<double> INDIRIM { get; set; }
        public Nullable<double> YEKUN { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
    }
}
