//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_SRG_SATICIFIRMA_006_04
    {
        public int CREF { get; set; }
        public string CSATICI { get; set; }
        public string CODE { get; set; }
        public string CADI { get; set; }
        public Nullable<double> NETTUTAR { get; set; }
    }
}
