//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSrG_GenelCari_006_04
    {
        public int LOGICALREF { get; set; }
        public string FirmaKodu { get; set; }
        public string FirmaAdı { get; set; }
        public string Plasiyer { get; set; }
        public string Telefon { get; set; }
        public string Sehiri { get; set; }
        public Nullable<double> Borç { get; set; }
        public Nullable<double> Alacak { get; set; }
        public double Bakiye { get; set; }
        public double ONCEKIBAKIYE { get; set; }
        public double CIKISLAR { get; set; }
        public double GIRISLER { get; set; }
        public System.DateTime SONTAHSILATTARIHI { get; set; }
        public System.DateTime SONFATURATARIHI { get; set; }
        public int FATURASAYISI { get; set; }
        public double YILLIKSATISTUTARI { get; set; }
        public double ACIKRISK { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
    }
}
