//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class JSRG_CEK_SENET_DURUM
    {
        public Nullable<System.DateTime> TARIH { get; set; }
        public string NEWSERINO { get; set; }
        public Nullable<short> DOC { get; set; }
        public string BANKASI { get; set; }
        public Nullable<System.DateTime> VADE { get; set; }
        public Nullable<double> TUTAR { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public string MAGAZA { get; set; }
        public string CARI { get; set; }
        public int LOGICALREF { get; set; }
        public Nullable<int> CARDREF { get; set; }
        public Nullable<short> CARDMD { get; set; }
        public string Plasiyer { get; set; }
    }
}
