//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_006_04_ORFICHE
    {
        public int LOGICALREF { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public string FICHENO { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<int> TIME_ { get; set; }
        public string DOCODE { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public Nullable<int> RECVREF { get; set; }
        public Nullable<int> ACCOUNTREF { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<short> SOURCEINDEX { get; set; }
        public Nullable<short> SOURCECOSTGRP { get; set; }
        public Nullable<short> UPDCURR { get; set; }
        public Nullable<double> ADDDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTS { get; set; }
        public Nullable<double> TOTALDISCOUNTED { get; set; }
        public Nullable<double> ADDEXPENSES { get; set; }
        public Nullable<double> TOTALEXPENSES { get; set; }
        public Nullable<double> TOTALPROMOTIONS { get; set; }
        public Nullable<double> TOTALVAT { get; set; }
        public Nullable<double> GROSSTOTAL { get; set; }
        public Nullable<double> NETTOTAL { get; set; }
        public Nullable<double> REPORTRATE { get; set; }
        public Nullable<double> REPORTNET { get; set; }
        public string GENEXP1 { get; set; }
        public string GENEXP2 { get; set; }
        public string GENEXP3 { get; set; }
        public string GENEXP4 { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<int> PAYDEFREF { get; set; }
        public Nullable<short> PRINTCNT { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<int> SALESMANREF { get; set; }
        public string SHPTYPCOD { get; set; }
        public string SHPAGNCOD { get; set; }
        public Nullable<short> GENEXCTYP { get; set; }
        public Nullable<short> LINEEXCTYP { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<short> FACTORYNR { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<int> SHIPINFOREF { get; set; }
        public string CUSTORDNO { get; set; }
        public Nullable<short> SENDCNT { get; set; }
        public Nullable<short> DLVCLIENT { get; set; }
        public string DOCTRACKINGNR { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public string ORGLOGOID { get; set; }
        public Nullable<int> OFFERREF { get; set; }
        public Nullable<int> OFFALTREF { get; set; }
        public Nullable<short> TYP { get; set; }
        public Nullable<short> ALTNR { get; set; }
        public Nullable<double> ADVANCEPAYM { get; set; }
        public Nullable<short> TRCURR { get; set; }
        public Nullable<double> TRRATE { get; set; }
        public Nullable<double> TRNET { get; set; }
        public Nullable<short> PAYMENTTYPE { get; set; }
        public Nullable<short> ONLYONEPAYLINE { get; set; }
        public Nullable<short> OPSTAT { get; set; }
        public Nullable<short> WITHPAYTRANS { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public Nullable<int> WFLOWCRDREF { get; set; }
        public Nullable<short> UPDTRCURR { get; set; }
        public Nullable<short> AFFECTCOLLATRL { get; set; }
        public Nullable<System.DateTime> POFFERBEGDT { get; set; }
        public Nullable<System.DateTime> POFFERENDDT { get; set; }
        public string REVISNR { get; set; }
        public Nullable<short> LASTREVISION { get; set; }
        public Nullable<short> CHECKAMOUNT { get; set; }
        public Nullable<int> SLSOPPRREF { get; set; }
        public Nullable<int> SLSACTREF { get; set; }
        public Nullable<int> SLSCUSTREF { get; set; }
        public Nullable<short> AFFECTRISK { get; set; }
        public Nullable<double> TOTALADDTAX { get; set; }
        public Nullable<double> TOTALEXADDTAX { get; set; }
        public Nullable<short> APPROVE { get; set; }
        public Nullable<System.DateTime> APPROVEDATE { get; set; }
    }
}
