//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_006_04_ORFLINE
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> STOCKREF { get; set; }
        public Nullable<int> ORDFICHEREF { get; set; }
        public Nullable<int> CLIENTREF { get; set; }
        public Nullable<short> LINETYPE { get; set; }
        public Nullable<int> PREVLINEREF { get; set; }
        public Nullable<short> PREVLINENO { get; set; }
        public Nullable<short> DETLINE { get; set; }
        public Nullable<short> LINENO_ { get; set; }
        public Nullable<short> TRCODE { get; set; }
        public Nullable<System.DateTime> DATE_ { get; set; }
        public Nullable<int> TIME_ { get; set; }
        public Nullable<short> GLOBTRANS { get; set; }
        public Nullable<short> CALCTYPE { get; set; }
        public Nullable<int> CENTERREF { get; set; }
        public Nullable<int> ACCOUNTREF { get; set; }
        public Nullable<int> VATACCREF { get; set; }
        public Nullable<int> VATCENTERREF { get; set; }
        public Nullable<int> PRACCREF { get; set; }
        public Nullable<int> PRCENTERREF { get; set; }
        public Nullable<int> PRVATACCREF { get; set; }
        public Nullable<int> PRVATCENREF { get; set; }
        public Nullable<int> PROMREF { get; set; }
        public string SPECODE { get; set; }
        public string DELVRYCODE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<double> TOTAL { get; set; }
        public Nullable<double> SHIPPEDAMOUNT { get; set; }
        public Nullable<double> DISCPER { get; set; }
        public Nullable<double> DISTCOST { get; set; }
        public Nullable<double> DISTDISC { get; set; }
        public Nullable<double> DISTEXP { get; set; }
        public Nullable<double> DISTPROM { get; set; }
        public Nullable<double> VAT { get; set; }
        public Nullable<double> VATAMNT { get; set; }
        public Nullable<double> VATMATRAH { get; set; }
        public string LINEEXP { get; set; }
        public Nullable<int> UOMREF { get; set; }
        public Nullable<int> USREF { get; set; }
        public Nullable<double> UINFO1 { get; set; }
        public Nullable<double> UINFO2 { get; set; }
        public Nullable<double> UINFO3 { get; set; }
        public Nullable<double> UINFO4 { get; set; }
        public Nullable<double> UINFO5 { get; set; }
        public Nullable<double> UINFO6 { get; set; }
        public Nullable<double> UINFO7 { get; set; }
        public Nullable<double> UINFO8 { get; set; }
        public Nullable<short> VATINC { get; set; }
        public Nullable<short> CLOSED { get; set; }
        public Nullable<short> DORESERVE { get; set; }
        public Nullable<short> INUSE { get; set; }
        public Nullable<System.DateTime> DUEDATE { get; set; }
        public Nullable<short> PRCURR { get; set; }
        public Nullable<double> PRPRICE { get; set; }
        public Nullable<double> REPORTRATE { get; set; }
        public Nullable<int> BILLEDITEM { get; set; }
        public Nullable<int> PAYDEFREF { get; set; }
        public Nullable<int> EXTENREF { get; set; }
        public Nullable<short> CPSTFLAG { get; set; }
        public Nullable<short> SOURCEINDEX { get; set; }
        public Nullable<short> SOURCECOSTGRP { get; set; }
        public Nullable<short> BRANCH { get; set; }
        public Nullable<short> DEPARTMENT { get; set; }
        public Nullable<double> LINENET { get; set; }
        public Nullable<int> SALESMANREF { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<int> DREF { get; set; }
        public Nullable<short> TRGFLAG { get; set; }
        public Nullable<short> SITEID { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<short> FACTORYNR { get; set; }
        public Nullable<int> WFSTATUS { get; set; }
        public Nullable<short> NETDISCFLAG { get; set; }
        public Nullable<double> NETDISCPERC { get; set; }
        public Nullable<double> NETDISCAMNT { get; set; }
        public Nullable<int> CONDITIONREF { get; set; }
        public Nullable<double> DISTRESERVED { get; set; }
        public Nullable<double> ONVEHICLE { get; set; }
        public Nullable<int> CAMPAIGNREFS1 { get; set; }
        public Nullable<int> CAMPAIGNREFS2 { get; set; }
        public Nullable<int> CAMPAIGNREFS3 { get; set; }
        public Nullable<int> CAMPAIGNREFS4 { get; set; }
        public Nullable<int> CAMPAIGNREFS5 { get; set; }
        public Nullable<int> POINTCAMPREF { get; set; }
        public Nullable<double> CAMPPOINT { get; set; }
        public Nullable<int> PROMCLASITEMREF { get; set; }
        public Nullable<short> REASONFORNOTSHP { get; set; }
        public Nullable<int> CMPGLINEREF { get; set; }
        public Nullable<double> PRRATE { get; set; }
        public Nullable<double> GROSSUINFO1 { get; set; }
        public Nullable<double> GROSSUINFO2 { get; set; }
        public Nullable<short> CANCELLED { get; set; }
        public Nullable<double> DEMPEGGEDAMNT { get; set; }
        public Nullable<short> TEXTINC { get; set; }
        public Nullable<int> OFFERREF { get; set; }
        public Nullable<short> ORDERPARAM { get; set; }
        public Nullable<int> ITEMASGREF { get; set; }
        public Nullable<double> EXIMAMOUNT { get; set; }
        public Nullable<int> OFFTRANSREF { get; set; }
        public Nullable<double> ORDEREDAMOUNT { get; set; }
        public string ORGLOGOID { get; set; }
        public Nullable<short> TRCURR { get; set; }
        public Nullable<double> TRRATE { get; set; }
        public Nullable<short> WITHPAYTRANS { get; set; }
        public Nullable<int> PROJECTREF { get; set; }
        public Nullable<int> POINTCAMPREFS1 { get; set; }
        public Nullable<int> POINTCAMPREFS2 { get; set; }
        public Nullable<int> POINTCAMPREFS3 { get; set; }
        public Nullable<int> POINTCAMPREFS4 { get; set; }
        public Nullable<double> CAMPPOINTS1 { get; set; }
        public Nullable<double> CAMPPOINTS2 { get; set; }
        public Nullable<double> CAMPPOINTS3 { get; set; }
        public Nullable<double> CAMPPOINTS4 { get; set; }
        public Nullable<int> CMPGLINEREFS1 { get; set; }
        public Nullable<int> CMPGLINEREFS2 { get; set; }
        public Nullable<int> CMPGLINEREFS3 { get; set; }
        public Nullable<int> CMPGLINEREFS4 { get; set; }
        public Nullable<int> PRCLISTREF { get; set; }
        public Nullable<short> AFFECTCOLLATRL { get; set; }
        public Nullable<short> FCTYP { get; set; }
        public Nullable<short> PURCHOFFNR { get; set; }
        public Nullable<int> DEMFICHEREF { get; set; }
        public Nullable<int> DEMTRANSREF { get; set; }
        public Nullable<short> ALTPROMFLAG { get; set; }
        public Nullable<int> VARIANTREF { get; set; }
        public Nullable<int> REFLVATACCREF { get; set; }
        public Nullable<int> REFLVATOTHACCREF { get; set; }
        public Nullable<short> PRIORITY { get; set; }
        public Nullable<short> AFFECTRISK { get; set; }
        public Nullable<int> BOMREF { get; set; }
        public Nullable<int> BOMREVREF { get; set; }
        public Nullable<int> ROUTINGREF { get; set; }
        public Nullable<int> OPERATIONREF { get; set; }
        public Nullable<int> WSREF { get; set; }
        public Nullable<double> ADDTAXRATE { get; set; }
        public Nullable<double> ADDTAXCONVFACT { get; set; }
        public Nullable<double> ADDTAXAMOUNT { get; set; }
        public Nullable<int> ADDTAXACCREF { get; set; }
        public Nullable<int> ADDTAXCENTERREF { get; set; }
        public Nullable<short> ADDTAXAMNTISUPD { get; set; }
        public Nullable<double> ADDTAXDISCAMOUNT { get; set; }
        public Nullable<double> EXADDTAXRATE { get; set; }
        public Nullable<double> EXADDTAXCONVF { get; set; }
        public Nullable<double> EXADDTAXAMNT { get; set; }
        public Nullable<short> EUVATSTATUS { get; set; }
        public Nullable<double> ADDTAXVATMATRAH { get; set; }
    }
}
