//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_006_04_ORFICHESEQ
    {
        public Nullable<int> ID { get; set; }
        public int LASTLREF { get; set; }
    }
}
