//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_SLSMAN
    {
        public int LOGICALREF { get; set; }
        public string CODE { get; set; }
        public string DEFINITION_ { get; set; }
        public Nullable<short> CARDTYPE { get; set; }
        public string SPECODE { get; set; }
        public string CYPHCODE { get; set; }
        public string POSITION_ { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_CREADEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_CREATEDSEC { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CAPIBLOCK_MODIFIEDDATE { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDHOUR { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDMIN { get; set; }
        public Nullable<short> CAPIBLOCK_MODIFIEDSEC { get; set; }
        public Nullable<short> ACTIVE { get; set; }
        public Nullable<int> SITEID { get; set; }
        public Nullable<int> ORGLOGICREF { get; set; }
        public Nullable<short> USERID { get; set; }
        public Nullable<short> DEPTID { get; set; }
        public Nullable<short> DIVISID { get; set; }
        public Nullable<short> FIRMNR { get; set; }
        public Nullable<short> RECSTATUS { get; set; }
        public Nullable<short> TYP { get; set; }
    }
}
