//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOGOKAMPEntities1 : DbContext
    {
        public LOGOKAMPEntities1()
            : base("name=LOGOKAMPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZTbLUseR> ZTbLUseR { get; set; }
        public virtual DbSet<Z_SipLine> Z_SipLine { get; set; }
        public virtual DbSet<SRG_SipLine> SRG_SipLine { get; set; }
    }
}
