//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRG_SipLine
    {
        public int LOGICALREF { get; set; }
        public Nullable<int> SIPID { get; set; }
        public string FICHENO { get; set; }
        public System.DateTime DATE_ { get; set; }
        public string CLIENTREF { get; set; }
        public string STOCKREF { get; set; }
        public string STOCKCODE { get; set; }
        public string STOCKNAME { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string BIRIM { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> KDVPRICE { get; set; }
        public Nullable<decimal> VINDORAN { get; set; }
        public Nullable<decimal> KAMPBRFiyat { get; set; }
        public Nullable<decimal> KAMPKDVBrFiyat { get; set; }
        public Nullable<decimal> SATIRTUTARI { get; set; }
        public Nullable<decimal> SATIRKDVTUTARI { get; set; }
        public string LINEEXP { get; set; }
        public Nullable<int> Durum { get; set; }
        public Nullable<System.DateTime> ADDDATE { get; set; }
        public Nullable<System.DateTime> EDITDATE { get; set; }
        public Nullable<int> AKTARIM { get; set; }
        public Nullable<int> CURRID { get; set; }
        public Nullable<decimal> CURRRATE { get; set; }
        public Nullable<decimal> LISTFIYAT { get; set; }
        public Nullable<decimal> LISTTLFIYAT { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<decimal> TOPTLFIYAT { get; set; }
        public string TRADINGGRP { get; set; }
        public Nullable<int> DIVISION { get; set; }
        public Nullable<int> VATINC { get; set; }
        public Nullable<int> KIMDEN { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> TeklifFlag { get; set; }
        public string OdemeSekli { get; set; }
        public Nullable<decimal> MIKINDORAN { get; set; }
        public Nullable<int> ADRESREF { get; set; }
        public string TeslimDurumu { get; set; }
        public Nullable<decimal> SEVKMIKTARI { get; set; }
        public string DOSYA { get; set; }
        public string NakliyeTipi { get; set; }
        public string Adres { get; set; }
        public Nullable<int> Vade { get; set; }
        public Nullable<int> ISEDIT { get; set; }
        public Nullable<int> USERID { get; set; }
        public string USERAdi { get; set; }
        public string SAPKODU { get; set; }
        public string MUSTERISIPARIS { get; set; }
    }
}
