//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class XX_SRG_Cari_HDurum_006
    {
        public int LOGICALREF { get; set; }
        public string M_Kodu { get; set; }
        public string Müşteri_Adı { get; set; }
        public string Şehiri { get; set; }
        public string Ilce { get; set; }
        public string Plasiyer { get; set; }
        public double Bakiye { get; set; }
        public double GecikenTutar { get; set; }
        public Nullable<double> GecikmeGünü { get; set; }
        public double Bekleyen { get; set; }
        public double HaftalikTahsilat { get; set; }
        public double AyTahsilatı { get; set; }
        public double SonrakiAy { get; set; }
        public double DigerAylar { get; set; }
        public double ORTVade { get; set; }
        public Nullable<System.DateTime> Vade_Gunu { get; set; }
    }
}
