//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class XX_SRG_CLFGenel_006
    {
        public string CariSatici { get; set; }
        public Nullable<double> Nakit { get; set; }
        public Nullable<double> Cek { get; set; }
        public Nullable<double> Senet { get; set; }
        public Nullable<double> KK { get; set; }
        public Nullable<double> Havale { get; set; }
        public Nullable<double> Dekont { get; set; }
        public Nullable<int> PlasiyerCarisi { get; set; }
        public double PlasiyerBakiyesi { get; set; }
    }
}
