//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PB2B.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZTbLUseR
    {
        public int UserId { get; set; }
        public string Adi { get; set; }
        public string Sifresi { get; set; }
        public Nullable<int> SipID { get; set; }
        public string SipStr { get; set; }
        public Nullable<int> Yetkisi { get; set; }
        public Nullable<int> Muhasebe { get; set; }
        public string CariSTR { get; set; }
        public string CLIENTREF { get; set; }
        public Nullable<int> SLSREF { get; set; }
        public string SLSCODE { get; set; }
        public string SLSNAME { get; set; }
        public Nullable<int> GrupID { get; set; }
        public Nullable<int> GrupSEQ { get; set; }
        public string GrupSTR { get; set; }
        public string KullanıcıEkle { get; set; }
        public string DosyaYukle { get; set; }
        public Nullable<int> TAHID { get; set; }
        public Nullable<int> TERMINALSAYI { get; set; }
        public string CARIKILIT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FCYETKI { get; set; }
        public Nullable<int> TUYETKI { get; set; }
        public Nullable<int> ISKONTOTABLOYETKI { get; set; }
    }
}
